# Generated by Django 5.2.4 on 2025-08-24 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='اسم الدفعة')),
                ('num', models.PositiveIntegerField(verbose_name='رقم الدفعة')),
                ('is_open_reg', models.BooleanField(default=False, verbose_name='فتح التسجيل')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('track_1', 'المساق الأول'), ('track_2', 'المساق الثاني'), ('track_3', 'المساق الثالث')], max_length=100, verbose_name='المساق')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.batch', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'مساق',
                'verbose_name_plural': 'المساقات',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='رقم المرحلة')),
                ('is_active', models.BooleanField(default=False, verbose_name='فتح الرحلة')),
                ('num_ques', models.PositiveIntegerField(verbose_name='عدد الأسئلة')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tracks.track', verbose_name='المساق')),
            ],
            options={
                'verbose_name': 'مرحلة',
                'verbose_name_plural': 'المراحل',
            },
        ),
    ]
