# Generated by Django 5.2.4 on 2025-08-24 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheikhs', '0001_initial'),
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rwia', models.CharField(choices=[('hfs', 'حفص'), ('wrsh', 'ورش'), ('qalon', 'قالون')], max_length=15, verbose_name='الرواية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('need_help', 'محتاج متابعة'), ('excluded', 'مستبعد'), ('withdrawn', 'منسحب'), ('graduated', 'متخرج')], default='active', max_length=20, verbose_name='الحالة')),
                ('nsap', models.PositiveIntegerField(blank=True, null=True, verbose_name='المحفوظ')),
                ('sheikh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='sheikhs.sheikh', verbose_name='الشيخ')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracks.track', verbose_name='المساق')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_User', to=settings.AUTH_USER_MODEL, verbose_name='حساب الطالب')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='العنوان')),
                ('message', models.CharField(max_length=400, verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(limit_choices_to={'user': True}, on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_excuse', models.CharField(choices=[('sick', 'مرض'), ('death', 'حالة وفاة'), ('work', 'ظروف العمل'), ('study', 'ظروف دراسية'), ('power', 'انقطاع الكهرباء'), ('other', 'أخرى')], max_length=100, verbose_name='نوع العذر')),
                ('message', models.CharField(max_length=2000, verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('on', 'تحت المراجعة'), ('rejected', 'مرفوض'), ('ok', 'مقبول')], default='on', max_length=50, verbose_name='الحالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'عذر',
                'verbose_name_plural': 'الأعذار',
            },
        ),
    ]
