# Generated by Django 5.2.4 on 2025-08-24 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('followups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('need_help', 'يحتاج متابعة'), ('excused', 'معتذر مؤقتا'), ('withdrawn', 'منسحب')], default='active', max_length=20, verbose_name='الحالة')),
                ('followup_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='followups.followupsupervisor', verbose_name='مشرف المتابعة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_User', to=settings.AUTH_USER_MODEL, verbose_name='حساب المشرف')),
            ],
            options={
                'verbose_name': 'مشرف',
                'verbose_name_plural': 'المشرفون',
            },
        ),
    ]
