# Generated by Django 5.2.4 on 2025-08-24 13:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'طالب'), ('sheikh', 'شيخ'), ('supervisor', 'مشرف'), ('followup', 'مشرف متابعة'), ('admin', 'إداري')], default='student', max_length=20, verbose_name='الدور')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='الاسم')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=50, null=True, verbose_name='النوع')),
                ('country', models.CharField(choices=[('egypt', 'مصر'), ('jordan', 'الأردن'), ('uae', 'الإمارات'), ('bahrain', 'البحرين'), ('algeria', 'الجزائر'), ('sudan', 'السودان'), ('iraq', 'العراق'), ('kuwait', 'الكويت'), ('morocco', 'المغرب'), ('saudi_arabia', 'السعودية'), ('tunisia', 'تونس'), ('oman', 'عُمان'), ('palestine', 'فلسطين'), ('qatar', 'قطر'), ('lebanon', 'لبنان'), ('libya', 'ليبيا'), ('mauritania', 'موريتانيا'), ('yemen', 'اليمن'), ('djibouti', 'جيبوتي'), ('comoros', 'جزر القمر'), ('somalia', 'الصومال'), ('syria', 'سوريا'), ('turkey', 'تركيا'), ('pakistan', 'باكستان'), ('iran', 'إيران'), ('afghanistan', 'أفغانستان'), ('indonesia', 'إندونيسيا'), ('malaysia', 'ماليزيا'), ('niger', 'النيجر'), ('senegal', 'السنغال'), ('bangladesh', 'بنغلاديش'), ('nigeria', 'نيجيريا'), ('mali', 'مالي'), ('azerbaijan', 'أذربيجان'), ('albania', 'ألبانيا'), ('kosovo', 'كوسوفو'), ('germany', 'ألمانيا'), ('usa', 'الولايات المتحدة'), ('france', 'فرنسا'), ('italy', 'إيطاليا'), ('china', 'الصين'), ('canada', 'كندا'), ('india', 'الهند'), ('uk', 'المملكة المتحدة'), ('spain', 'إسبانيا'), ('russia', 'روسيا'), ('brazil', 'البرازيل'), ('argentina', 'الأرجنتين'), ('australia', 'أستراليا'), ('japan', 'اليابان'), ('south_korea', 'كوريا الجنوبية')], max_length=50, verbose_name='الدولة')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='البريد الإلكتروني')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الحساب')),
                ('tele', models.CharField(blank=True, max_length=20, null=True, verbose_name='معرف التليجرام')),
                ('teleid', models.BigIntegerField(blank=True, null=True, verbose_name='حساب التليجرام')),
                ('join_date', models.DateField(auto_now=True, verbose_name='تاريخ التسجيل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExcuseTeleAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'followup'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب مشرف المتابعة')),
            ],
            options={
                'verbose_name': 'مشرف أعذار',
                'verbose_name_plural': 'مشرفوا الأعذار',
            },
        ),
    ]
