# Generated by Django 5.2.4 on 2025-08-24 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheikhs', '0001_initial'),
        ('students', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الدرجة')),
                ('status', models.CharField(blank=True, choices=[('passed', 'ناجح'), ('Failed', 'راسب')], max_length=50, null=True, verbose_name='الحالة')),
                ('memorization_level', models.CharField(choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدا'), ('good', 'جيد'), ('fair', 'مقبول'), ('weak', 'ضعيف')], max_length=50, verbose_name='تقدير الحفظ')),
                ('tajweed_level', models.CharField(choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدا'), ('good', 'جيد'), ('fair', 'مقبول'), ('weak', 'ضعيف')], max_length=50, verbose_name='تقدير التجويد')),
                ('notes', models.TextField(verbose_name='الملاحظات')),
            ],
            options={
                'verbose_name': 'تقييم اختبار',
                'verbose_name_plural': 'تقييمات الاختبارات',
            },
        ),
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarkh', models.DateField(verbose_name='التاريخ')),
                ('from_hour', models.TimeField(verbose_name='من الساعة')),
                ('to_hour', models.TimeField(verbose_name='إلى الساعة')),
                ('student_num', models.PositiveIntegerField(verbose_name='عدد الطلاب')),
                ('sheikh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheikhs.sheikh', verbose_name='الشيخ')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'الاختبارات',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='رقم السؤال')),
                ('alarm_count', models.PositiveIntegerField(default=0, verbose_name='عدد التنبيهات')),
                ('mistake_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأخطاء')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.examres', verbose_name='الاختبار')),
            ],
            options={
                'verbose_name': 'درجة سؤال',
                'verbose_name_plural': 'درجات الأسئلة',
            },
        ),
        migrations.CreateModel(
            name='ExamStu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsap', models.PositiveIntegerField(default=0, verbose_name='النصاب')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='رقم المحاولة')),
                ('book_date', models.DateTimeField(auto_now=True, verbose_name='تاريخ الحجز')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examdate', verbose_name='الموعد')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracks.stage', verbose_name='المرحلة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'طالب باختبار',
                'verbose_name_plural': 'طلاب الاختبارات',
            },
        ),
        migrations.AddField(
            model_name='examres',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_res', to='exams.examstu', verbose_name='الموعد'),
        ),
    ]
