# Generated by Django 5.2.4 on 2025-08-24 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheikh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rwia', models.CharField(choices=[('hfs', 'حفص'), ('wrsh', 'ورش'), ('qalon', 'قالون')], max_length=30, verbose_name='الرواية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('need_help', 'يحتاج متابعة'), ('excused', 'معتذر مؤقتا'), ('withdrawn', 'منسحب')], default='active', max_length=20, verbose_name='الحالة')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheikhs', to='supervisors.supervisor', verbose_name='المشرف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sheikh_User', to=settings.AUTH_USER_MODEL, verbose_name='حساب الشيخ')),
            ],
            options={
                'verbose_name': 'شيخ',
                'verbose_name_plural': 'الشيوخ',
            },
        ),
    ]
